version: '3'
services:  
  jenkins-x64: &jenkins
    image: p4telj/jenkins:x64
    container_name: jenkins-container
    hostname: jenkins-container
    restart: always
    build:
      context: ./jenkins
      dockerfile: Dockerfile-x64
    ports:
      - "9999:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    environment:
      - "JENKINS_USER=501"
  jenkins-arm32:
    <<: *jenkins
    image: p4telj/jenkins:arm32
    build:
      context: ./jenkins
      dockerfile: Dockerfile-arm32
  mysql-x64: &mysql
    image: p4telj/mysql:x64
    container_name: mysql-container
    hostname: mysql-container
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile-x64
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=password
  gitea-x64: &gitea
    image: gitea/gitea:latest
    container_name: gitea-container
    hostname: gitea-container
    restart: always
    volumes:
      - ./gitea/data:/data
    ports:
      - "9998:3000"
      - "9997:22"
  gitea-arm32:
    <<: *gitea
    image: p4telj/gitea:arm32
    build:
      context: ./gitea
      dockerfile: Dockerfile-arm32
